### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by ChrisRackauckas** [wildart/ManifoldLearning.jl#10]

**Comment by abhijithch** [comment]
Bump

**Comment by ViralBShah** [comment]
Bump - or maybe add other collaborators to this repo? We are incorporating this package into training materials, and need a new tagged version.

**Comment by AzamatB** [comment]
I am interested in collaborating and maintaining this repo. Could you add me to collaborators @wildart ?

**Comment by wildart** [comment]
@AzamatB You can start with submitting relevant PRs.

**Comment by ChrisRackauckas** [comment]
Tags cannot be set via PRs. A repo maintainer needs to tag releases. I would suggest setting up attobot.

https://github.com/attobot/attobot

With attobot, the process becomes quite simple and automated.

**Comment by wildart** [comment]
@ChrisRackauckas You proposed somewhere to transfer this package in JuliaStats. I have no problem with that. This will clear a bit my plate.

**Comment by simonschoelly** [comment]
May I ask, what is the status here? I think it would be great, if we had a new tag.

**Comment by wildart** [comment]
I started preparation for release 1.0. I'm going to finalize API interface, and fix docs. After that a new release will be issued.

Meanwhile, I tagged  version compatible with 0.7/1.0 as v0.2.0.

**Comment by wildart** [comment]
@JuliaRegistrator register()

**Comment by wildart** [comment]
@JuliaRegistrator register()

**Comment by wildart** [comment]
@JuliaRegistrator register()
