### ISSUE TITLE
Fit / transform interface for embeddings

### ISSUE THREAD

**Issue by VPetukhov** [wildart/ManifoldLearning.jl#12]
Hi,

Thank you for this package! Though it would be great to be able to split `fit` and `transform` steps, where it's possible from the algorithm side (like in [sklearn implementation](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.Isomap.html) of isomap). Great benefit of this algorithm is slow `fit` and fast `transform` steps. So, on really large data, you can learn embedding only on small subset and than transform the whole dataset. 

Just for reference, here is [sklearn code](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/manifold/isomap.py#L201) with comments and clear instructions on how to do that.

**Comment by wildart** [comment]
That would require to rewrite Isomap to use out-of-sample MDS transformation or use (K)PCA instead of MDS. Either options is possible as soon as particular extensions will be implemented in MultivariateStats.

**Comment by wildart** [comment]
Out-of-sample embedding for Isomap available in the recent version. See [`transform(M,X)`](https://wildart.github.io/ManifoldLearning.jl/dev/isomap/#MultivariateStats.transform-Union{Tuple{T},%20Tuple{Isomap,Union{AbstractArray{T,1},%20AbstractArray{T,2}}}}%20where%20T%3C:Real) method.
