### ISSUE TITLE
Isomap transform fails with "Empty collection" error

### ISSUE THREAD

**Issue by VPetukhov** [wildart/ManifoldLearning.jl#13]
Hi,

I run Isomap on the data from [example.txt](https://github.com/wildart/ManifoldLearning.jl/files/2566048/example.txt). Here is the result
```julia
import DelimitedFiles: readdlm
using ManifoldLearning

example = readdlm("example.txt");
transformed = transform(Isomap, example, d=2)
```
```
ArgumentError: collection must be non-empty

Stacktrace:
 [1] _extrema_itr at ./operators.jl:447 [inlined]
 [2] _extrema_dims at ./multidimensional.jl:1455 [inlined]
 [3] #extrema#405 at ./multidimensional.jl:1453 [inlined]
 [4] extrema at ./multidimensional.jl:1453 [inlined]
 [5] #classical_mds#23(::Bool, ::Function, ::Array{Float64,2}, ::Int64) at /home/vp/.julia/packages/MultivariateStats/56OfE/src/cmds.jl:76
 [6] classical_mds(::Array{Float64,2}, ::Int64) at /home/vp/.julia/packages/MultivariateStats/56OfE/src/cmds.jl:63
 [7] top-level scope at In[84]:7
```

The reason is in 1142'nd element, which is kind of outlier, as far as I understood. Looks like something is wrong with distance matrix on [line 47](https://github.com/wildart/ManifoldLearning.jl/blob/master/src/isomap.jl#L47). But as this graph has single connected component, I can't understand why do we have infinite distances in the matrix.

---

BTW, why do you use your own functions for work with graphs and nearest neighbor search? For instance, [LightGraphs](https://github.com/JuliaGraphs/LightGraphs.jl) is optimized and well-tested. And [NearestNeighbors](https://github.com/KristofferC/NearestNeighbors.jl) package has amazing implementation on KD trees, which is really easy to use and works way faster than estimation of the whole distance matrix.

**Comment by wildart** [comment]
~~This error relates to a reduction step when `classical_mds` function from `MultivariateStats` is called.~~
Yes, the distance matrix has `Inf` values and MDS breaks which means my Dijkstra implementation has error.

**Comment by wildart** [comment]
Works in v0.4.0
