### ISSUE TITLE
DiffMap-error : k not defined

### ISSUE THREAD

**Issue by SidxA** [wildart/ManifoldLearning.jl#26]
Hello - Thanks for the package.
Following Problem:
The Diffusionmap example with its 3 parameters from the documentation.
Some X Matrix{Float64} (if it matters in this case 200x16) with
`Y = transform(DiffMap, X; d=2, t=1, ɛ=1.0)`
yields

`
UndefVarError: k not defined

Stacktrace:
 [1] top-level scope
   @ In[190]:5
 [2] eval
   @ ./boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
`

Even defining some global k does not ged rid of the error.

**Comment by wildart** [comment]
There is no `transform` method with such signature. You want to use `fit` prior using `transform`, i.e.

```julia
 Y = transform(fit(DiffMap, X; d=2, t=1, ɛ=1.0))
```

**Comment by SidxA** [comment]
Alright Great
I took the example from https://manifoldlearningjl.readthedocs.io/en/latest/diffmaps.html
where it states:
`using ManifoldLearning`
`#suppose X is a data matrix, with each observation in a column`
`#apply DiffMap transformation to the dataset`
`Y = transform(DiffMap, X; d=2, t=1, ɛ=1.0)`
Maybe I got confused on wether this DiffMap is of DiffMap type and has already been fitted.

now when I use `fit` instead
`using ManifoldLearning`
`Y = fit(DiffMap, rand(100,100), d=2, t=1, ɛ=1.0)`
the error displayed is 

MethodError: no method matching fit(::Type{DiffMap}, ::Matrix{Float64}; d=2, t=1, ε=1.0)
Closest candidates are:
  fit(::Type{DiffMap}, ::AbstractMatrix{T}; maxoutdim, t, α, ε) where T<:Real at /home/leo/.julia/packages/ManifoldLearning/vRIIU/src/diffmaps.jl:63 got unsupported keyword argument "d"
  fit(::StatsBase.StatisticalModel, ::Any...) at /home/leo/.julia/packages/StatsBase/IPydo/src/statmodels.jl:178 got unsupported keyword arguments "d", "t", "ε"
  fit(::Type{Isomap}, ::AbstractMatrix{T}; k, maxoutdim, nntype) where T<:Real at /home/leo/.julia/packages/ManifoldLearning/vRIIU/src/isomap.jl:49 got unsupported keyword arguments "d", "t", "ε"
  ...

Stacktrace:
 [1] kwerr(::NamedTuple{(:d, :t, :ε), Tuple{Int64, Int64, Float64}}, ::Function, ::Type, ::Matrix{Float64})
   @ Base ./error.jl:157
 [2] top-level scope
   @ In[11]:2
 [3] eval
   @ ./boot.jl:360 [inlined]
 [4] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094

**Comment by SidxA** [comment]
Alright I believe I have just been a little confused by the possibly outdated documentation.
With
`fit(DiffMap,rand(100,100),maxoutdim=2,t=1, α = 0.0, ɛ=1.0)`
Everything works fine - Thank you.

**Comment by SidxA** [comment]
Though I haven't been able to use the 'transform' properly yet.

**Comment by wildart** [comment]
After you fit a model, you use the resulting model object as the `transform` function parameter to get a reduced representation of the data.
