### ISSUE TITLE
OutOfMemoryError()

### ISSUE THREAD

**Issue by ChauhanT** [wildart/ManifoldLearning.jl#31]
Hi! 

I am trying to run `Isomap` on a dataset composed of about 2 million, 24-D datapoints, and I get an `OutOfMemoryError()`. Would you have some tricks/advice about how I can deal with this? I'd really like to use as many of these points as possible for manifold-estimation. 

Thank you!

**Comment by wildart** [comment]
You need to use kd-tree to optimize memory usage and efficiently calculate point distances. See here: https://github.com/wildart/ManifoldLearning.jl/tree/master/misc.

By default, a plain distance matrix is used in the algorithm which has `O(n^2)` space complexity, so unless you have 3.6Tb of memory for the distance matrix, you should not use default settings.

**Comment by ChauhanT** [comment]
Yeah, I am trying to use that wrapper around KDTree from NearestNeighbors.jl, but there are some errors in using the predict function with it. I am trying to figure them out for now.
