### ISSUE TITLE
Connected components

### ISSUE THREAD

**Issue by ChauhanT** [wildart/ManifoldLearning.jl#32]
Hi, 

I am working with some test data which gives me a `Found 2 connected components. Largest component is selected.` warning. The data has about 2000 vectors. However, when I run predict on the fitted transform, only 1000 vectors are returned. I am guessing this is because the largest component is selected. I am not very familiar with the algorithm, and was wondering if you could point me towards the paper/chapter that describes it. Furthermore, I would like to use both the components - is that possible ?  

Sorry, I would have liked to email you directly, but I can't find your contact information anywhere! :) 

Cheers

**Comment by wildart** [comment]
I assume from you other inquiry that you used Isomap. The Isomap algorithm estimates a low-dimensional manifold from a neighborhood graph of data points. One graph. So if you see the message that there are multiple connected components, try to connect them together  by increasing `k` parameter - [number of nearest neighbors](https://wildart.github.io/ManifoldLearning.jl/dev/isomap/#StatsAPI.fit-Union{Tuple{T},%20Tuple{Type{Isomap},AbstractArray{T,2}}}%20where%20T%3C:Real).

**Comment by ChauhanT** [comment]
Ah, right. I see. Thank you!
