### ISSUE TITLE
Problem with running lle.jl

### ISSUE THREAD

**Issue by finmod** [wildart/ManifoldLearning.jl#6]
Running the tests, I get this error:

LoadError: LoadError: DimensionMismatch("dimensions must match")
while loading C:\Users\Denis\Documents\Finmod\ManifoldLearning.jl-master\test\lle.jl, in expression starting on line 8
while loading In[1], in expression starting on line 12

 in promote_shape(::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}, ::Tuple{Base.OneTo{Int64}}) at .\operators.jl:406
 in promote_shape(::Tuple{Base.OneTo{Int64}}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}) at .\operators.jl:402
 in promote_shape(::SparseVector{Float64,Int64}, ::Array{Float64,2}) at .\operators.jl:397
 in _elementwise(::Base.#-, ::Type{Float64}, ::SparseVector{Float64,Int64}, ::Array{Float64,2}) at .\arraymath.jl:57
 in #transform#9(::Int64, ::Int64, ::Function, ::Type{ManifoldLearning.LLE}, ::Array{Float64,2}) at C:\Users\Denis.julia\v0.5\ManifoldLearning\src\lle.jl:82
 in (::MultivariateStats.#kw##transform)(::Array{Any,1}, ::MultivariateStats.#transform, ::Type{ManifoldLearning.LLE}, ::Array{Float64,2}) at .<missing>:0
 in include_from_node1(::String) at .\loading.jl:488
 in macro expansion; at .\In[1]:14 [inlined]
 in anonymous at .<missing>:?

**Comment by wildart** [comment]
Check latest master.
